### PR TITLE
My changes

### PR DESCRIPTION
**Pull request by Finado**
Add background color to the menu
Add logo
Add membership registration form

### CODE REVIEW

**Comment by Finado** [comment]
Add background color to the menu
Add logo
Add membership registration form

**Comment by MrHeart** [comment]
ok, nice @Finado . This one, does it have the changes made by @MrObele? And also please create a new pull request targeting the dev branch not the master branch.  Thanks for understanding

**Comment by timonology** [comment]
Great one. Campers

**Comment by MrHeart** [comment]
I'm in love with the logo.  Pls do pull the latest changes and create a new pull request fast.  Even if it is only with the logo. Thanks

**Pull request closed without merging**
